set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(ARM_NONE_EABI_ROOT "" CACHE PATH "Root directory of an Arm GNU toolchain (contains bin/arm-none-eabi-gcc)")

if(ARM_NONE_EABI_ROOT)
  file(TO_CMAKE_PATH "${ARM_NONE_EABI_ROOT}" ARM_NONE_EABI_ROOT)
  set(_ARM_GCC_CANDIDATE "${ARM_NONE_EABI_ROOT}/bin/arm-none-eabi-gcc")
  set(_ARM_GXX_CANDIDATE "${ARM_NONE_EABI_ROOT}/bin/arm-none-eabi-g++")
  set(_ARM_OBJCOPY_CANDIDATE "${ARM_NONE_EABI_ROOT}/bin/arm-none-eabi-objcopy")
  set(_ARM_SIZE_CANDIDATE "${ARM_NONE_EABI_ROOT}/bin/arm-none-eabi-size")
endif()

if(NOT CMAKE_C_COMPILER)
  if(DEFINED _ARM_GCC_CANDIDATE AND EXISTS "${_ARM_GCC_CANDIDATE}")
    set(CMAKE_C_COMPILER "${_ARM_GCC_CANDIDATE}")
  elseif(EXISTS "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-gcc")
    set(CMAKE_C_COMPILER "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-gcc")
  endif()
endif()

if(NOT CMAKE_C_COMPILER)
  find_program(ARM_NONE_EABI_GCC arm-none-eabi-gcc REQUIRED)
  set(CMAKE_C_COMPILER "${ARM_NONE_EABI_GCC}")
endif()

if(NOT CMAKE_CXX_COMPILER)
  if(DEFINED _ARM_GXX_CANDIDATE AND EXISTS "${_ARM_GXX_CANDIDATE}")
    set(CMAKE_CXX_COMPILER "${_ARM_GXX_CANDIDATE}")
  elseif(EXISTS "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-g++")
    set(CMAKE_CXX_COMPILER "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-g++")
  endif()
endif()

if(NOT CMAKE_CXX_COMPILER)
  find_program(ARM_NONE_EABI_GXX arm-none-eabi-g++ REQUIRED)
  set(CMAKE_CXX_COMPILER "${ARM_NONE_EABI_GXX}")
endif()

if(NOT CMAKE_ASM_COMPILER)
  set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
endif()

if(NOT CMAKE_OBJCOPY)
  if(DEFINED _ARM_OBJCOPY_CANDIDATE AND EXISTS "${_ARM_OBJCOPY_CANDIDATE}")
    set(CMAKE_OBJCOPY "${_ARM_OBJCOPY_CANDIDATE}" CACHE FILEPATH "objcopy tool")
  elseif(EXISTS "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-objcopy")
    set(CMAKE_OBJCOPY "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-objcopy" CACHE FILEPATH "objcopy tool")
  endif()
endif()

if(NOT CMAKE_OBJCOPY)
  find_program(ARM_NONE_EABI_OBJCOPY arm-none-eabi-objcopy REQUIRED)
  set(CMAKE_OBJCOPY "${ARM_NONE_EABI_OBJCOPY}" CACHE FILEPATH "objcopy tool")
endif()

if(NOT CMAKE_SIZE)
  if(DEFINED _ARM_SIZE_CANDIDATE AND EXISTS "${_ARM_SIZE_CANDIDATE}")
    set(CMAKE_SIZE "${_ARM_SIZE_CANDIDATE}" CACHE FILEPATH "size tool")
  elseif(EXISTS "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-size")
    set(CMAKE_SIZE "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin/arm-none-eabi-size" CACHE FILEPATH "size tool")
  endif()
endif()

if(NOT CMAKE_SIZE)
  find_program(ARM_NONE_EABI_SIZE arm-none-eabi-size)
  set(CMAKE_SIZE "${ARM_NONE_EABI_SIZE}" CACHE FILEPATH "size tool")
endif()

set(CMAKE_EXECUTABLE_SUFFIX ".elf")
